### PR TITLE
Allowing users to receive PublicKey and PrivateKey as JSON String

### PR DESCRIPTION
**Pull request by tpmccallum**
I noticed this request/issue < https://github.com/IronCoreLabs/recrypt-rs/issues/89 > , by @drbh , which mentioned being able to serialize and deserialize recrypt data structures (to store on disk etc.) 

I notice that @clintfred mentioned (in the aforementioned feature/issue) that "We would consider a PR for this, but it's not a priority at this point".

Please consider the following PR and advise on what is required to successfully merge this new functionality.

# What does this PR provide?
The aim of this PR is to provide users of recrypt-rs with a JSON/String representation of recrypt generated keys (PublicKey struct, PrivateKey struct etc.)
# How does it work?
To enable a feature called serde (to their application), users of recrypt will simple update their Cargo.toml to include this new feature. 
```
recrypt = { version = "~0.11.0",  features = ["serde"],  default-features = false }
```
# Syntax for representing keys as JSON/String
Once keys are generated, the following syntax can be used to generate JSON/String representation.
```
 serde_json::to_string(&priv_key).unwrap()
```

# Work performed so far
I have updated both recrypt-rs and gridiron so that they both implement serde as an optional feature. Users/calling-code can choose to take advantage of the feature in the event that they want to be able to read and write the **PrivateKey** and **PublicKey** fields to disk (or return these values back to the calling code etc.)

I have created a PR which demonstrates this serialization/deserialization. I hope this is helpful to the codebase and users. Here is a working implementation.

# main.rs
```rust
use recrypt::prelude::*;

fn main() {
    // create a new recrypt
    let mut recrypt = Recrypt::new();

    // generate a plaintext to encrypt
    let pt = recrypt.gen_plaintext();

    // generate a public/private keypair and some signing keys
    let (priv_key, pub_key) = recrypt.generate_key_pair().unwrap();
    println!("Private Key: {:?}", serde_json::to_string(&priv_key).unwrap());
    println!("Public Key: {:?}", serde_json::to_string(&pub_key).unwrap());
}
```
# Cargo.toml
```
[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
recrypt = { git= "https://github.com/tpmccallum/recrypt-rs", branch = "optional_serde_feature", version = "~0.11.0", features = ["wasm", "serde"], default-features = false }
```
# Output
```
Private Key: "{\"bytes\":[65,87,140,167,200,98,231,79,144,36,254,60,165,139,82,127,77,18,160,138,228,152,244,23,142,178,210,193,53,156,46,212],\"_internal_key\":{\"value\":{\"limbs\":[344237537,189664523,903829374,1976569010,712921401,287292289,1656743474,2113130108,110]}}}"
Public Key: "{\"x\":[28,6,74,23,3,173,239,177,82,1,81,76,208,140,83,102,200,169,71,97,43,161,15,107,145,224,154,54,84,122,83,96],\"y\":[82,96,170,240,15,127,153,54,205,154,91,30,65,67,49,78,192,73,156,207,50,216,33,34,175,107,174,35,108,164,2,185],\"_internal_key\":{\"value\":{\"x\":{\"limbs\":[556943096,1982674010,1216135794,1701197264,1016537482,1179852127,1656387065,390134280,99]},\"y\":{\"limbs\":[341939558,159841115,1987058143,76820373,1677678398,2112994737,1738790866,1872574136,89]},\"z\":{\"limbs\":[1123696276,871041335,1082750262,1179880934,640986614,1564709300,1793041940,1343582089,36]}}}}"
```

# Please note
The reason that I am using my github repo as the recrypt dependency in the above is example is that I also had to update gridiron so that `pub struct Monty` was serde compatible. There is a second PR for gridiron at https://github.com/IronCoreLabs/gridiron/pull/31 which will require merging so that recrypt and gridiron can interoperate.

# Moving forward
If it is Ok with you all I would like to work through all of this code to ensure that it adds features and functionality to your users but poses no risk or issues whatsoever. 

My next step is to run the tests (as apposed to just focussing on the PrivateKey PublicKey structs) and add this same serialization/deserialization functionality to other parts of recrypt and IronCoreLabs software. I believe that this will add value in terms of using this software as a service via RPC, JS, JSON etc.

# Feedback
Please provide any feedback and advice which will enable me to achieve the above goals. Happy to alter/update code as well as perform any testing required in order to complete this task.

Kind regards
Tim

### CODE REVIEW

**Comment by tpmccallum** [comment]
Hi,
I have begun the testing component of this PR. Below are the current results. As expected I will need to asses the impact of this PR's code changes and make some changes to ensure this PR adds features and functionality to your users but poses no risk or issues whatsoever.

# Tests for unmodified code
```bash
test result: ok. 304 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/concurrency-bfff982a714ff028
running 1 test
test generate_plaintexts ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Doc-tests recrypt
running 4 tests
test src/internal/mod.rs - internal::take_lock (line 1129) ... ignored
test src/prelude.rs - prelude (line 3) ... ok
test src/lib.rs -  (line 10) ... ok
test src/lib.rs -  (line 35) ... ok
test result: ok. 3 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```
# Tests for modified code
## Word requried
```
test api_480::test::private_key_augment_minus ... FAILED
test api_480::test::private_key_augment_plus ... FAILED
```
## Details
```
---- api_480::test::private_key_augment_minus stdout ----
thread 'api_480::test::private_key_augment_minus' panicked at 'assertion failed: `(left == right)`
  left: `PrivateKey { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], _internal_key: PrivateKey { value: Monty { limbs: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } } }`,
 right: `PrivateKey { bytes: [255, 252, 102, 100, 14, 36, 157, 158, 199, 90, 213, 41, 11, 129, 168, 93, 65, 87, 151, 185, 49, 37, 141, 160, 215, 139, 88, 162, 28, 66, 92, 223, 124, 253, 162, 136, 109, 61, 69, 196, 253, 34, 177, 68, 76, 71, 241, 66, 113, 131, 244, 107, 33, 223, 21, 244, 146, 22, 82, 240], _internal_key: PrivateKey { value: Monty { limbs: [1664270236, 2000252030, 1090821402, 1931849105, 603497556, 353738034, 1035879722, 172746491, 2028964027, 520224068, 1652497823, 2090593246, 1077086440, 292067764, 1866923812, 382] } } }`', src/api_480.rs:1547:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- api_480::test::private_key_augment_plus stdout ----
thread 'api_480::test::private_key_augment_plus' panicked at 'assertion failed: `(left == right)`
  left: `PrivateKey { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], _internal_key: PrivateKey { value: Monty { limbs: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } } }`,
 right: `PrivateKey { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3], _internal_key: PrivateKey { value: Monty { limbs: [1562186266, 585547362, 445363961, 373107586, 235669429, 70320378, 1725584133, 1655137918, 674554062, 1273113365, 570248622, 1027777883, 144574781, 808941279, 1969907309, 26235] } } }`', src/api_480.rs:1537:9

failures:
api_480::test::private_key_augment_minus
api_480::test::private_key_augment_plus
test result: FAILED. 302 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

I will go and see what needs to be done to rectify this asap. 
Chat soon

**Comment by tpmccallum** [comment]
Ok, all `cargo test` unit tests are passing now.
```
test result: ok. 304 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Running target/debug/deps/concurrency-98b5b9aae3540445

running 1 test
test generate_plaintexts ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Doc-tests recrypt

running 4 tests
test src/internal/mod.rs - internal::take_lock (line 1142) ... ignored
test src/prelude.rs - prelude (line 3) ... ok
test src/lib.rs -  (line 10) ... ok
test src/lib.rs -  (line 35) ... ok

test result: ok. 3 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

**Comment by clintfred** [comment]
Thanks for your contribution!

I would like to understand the dependency changes a little more as they constitute a hefty bump from 59 up to 93 dependent crates. I'm specifically questioning the dependency on `stdweb` (and `stdweb` related features flags).

As far as JSON output, I noticed that your examples are also outputting `_internal_key` for both `PublicKey` and `PrivateKey` which unnecessarily bloats your JSON representation. The _internal representation is simply duplicate information for faster internal processing. Omitting the `_internal_key` field is relatively straightforward on serialization, but derserialization will require you to write a custom deserializer, I think. Ultimately, you want to call something like `new` that takes the bytes and constructs the internal representation from it.

It occurs to me that once you stop serializing the `_internal_key` you won't need the changes in gridiron.

**Comment by tpmccallum** [comment]
Thank you @clintfred 
Please note that I have removed the stdweb related dependencies. These were added in an attempt to create a recrypt-rs demo [1], in the form of Rust + JavaScript hybrid app for Node.js. Being able to obtain the keys from recrypt as JSON/String will be a huge step forward in creating this demo.

In saying that, I will continue exploring additional solutions for the aforementioned demo outside of this specific PR to keep things neat and focused. 

I really like your suggestion about lightening the JSON output by removing the duplicate information (`_internal_key`). I think this approach is smart, and as you say it saves us from having to alter gridiron code. 

I will continue to achieve this and let you know when it is ready. 

Thanks again
Tim

[1] https://github.com/second-state/wasm-learning/tree/master/nodejs/recrypt_example

**Comment by clintfred** [comment]
Sounds good.

You've probably already seen these, but just in case:
* https://github.com/IronCoreLabs/recrypt-node-binding
* https://github.com/IronCoreLabs/recrypt-wasm-binding

**Comment by tpmccallum** [comment]
Just a quick note, when [this PR](https://github.com/IronCoreLabs/recrypt-rs/pull/115) is approved/merged I will rebase and then all of these tests will pass again. 

From that point I will continue with lightening up the JSON by removing the internal key etc.

Thanks so much!

**Comment by clintfred** [comment]
@tpmccallum #115 has been merged

**Comment by cjyar** [comment]
@tpmccallum The CI job broke because of a permissions problem; sorry for the trouble. I recommend you fetch from our master branch and then `git cherry-pick 16b85ad4c086f1bc17dad3021b63ecf381763242` to fix the problem.

**Comment by tpmccallum** [comment]
Thanks @cjyar 
All tests passing now :)

**Comment by tpmccallum** [comment]
Hi @clintfred 
I think that we might have a solution to the issue of unnecessarily outputting _internal_key for both PublicKey and PrivateKey.

It has become apparent that the pre-existing recrypt code actually provides a way of accessing the PublicKey and PrivateKey (without the _internal_key section). Specifically the [`.bytes_x_y()`](https://github.com/IronCoreLabs/recrypt-rs/blob/master/src/api_480.rs#L1007) and [`.bytes()`](https://github.com/IronCoreLabs/recrypt-rs/blob/master/src/api_480.rs#L1035) respectively. This is fantastic. 

I realised that with the implementation of this PR (optional serde feature) users can immediately take advantage of the pre-existing recrypt code to obtain PublicKey and PrivateKey as `JSON` / `String`, `Vec<u8>` and also `io` (as facilitated by serde) without the internal key data. 

Please find examples below. Please note, these are links to this PR's documentation which I have tested; they work great.

[Access PublicKey as JSON](https://github.com/IronCoreLabs/recrypt-rs/blob/81f5ddb4d9278e0581835a71448c8605125093f4/src/lib.rs#L105)
```rust
serde_json::to_string(&pub_key.bytes_x_y()).unwrap()
// returns "[[137, ... 78,107,146],[59, ... 34,71,16]]"
// note nested [[], []] structure
```

[Access PrivateKey as JSON](https://github.com/IronCoreLabs/recrypt-rs/blob/81f5ddb4d9278e0581835a71448c8605125093f4/src/lib.rs#L111)
```rust
serde_json::to_string(&priv_key.bytes()).unwrap()
// returns "[91, ... 178,104,87]")
```

[Access PublicKey as Vec<u8>](https://github.com/IronCoreLabs/recrypt-rs/blob/81f5ddb4d9278e0581835a71448c8605125093f4/src/lib.rs#L116)
```rust
serde_json::to_vec(&pub_key.bytes_x_y()).unwrap()
// returns [91, ...  54, 93, 93]
// note single [] structure
```

[Access PrivateKey as Vec<u8>](https://github.com/IronCoreLabs/recrypt-rs/blob/81f5ddb4d9278e0581835a71448c8605125093f4/src/lib.rs#L122)
```rust
serde_json::to_vec(&priv_key.bytes()).unwrap()
// returns [91, ... 56, 55, 93]
```
Given the above, I am really happy with this PR as is. 

Just a quick reminder that this PR requires that [the related gridiron PR](https://github.com/IronCoreLabs/gridiron/pull/31) be merged also; they go hand in hand.

As usual all thoughts, ideas and suggestions are more than welcome.

Kind regards
Tim

**Comment by clintfred** [comment]
Perhaps I am missing something (and if I am, apologies), but I don't think the serde support in the PR is needed for what you are suggesting. 

Here is a [new test](https://github.com/IronCoreLabs/recrypt-rs/blob/e723499c7bcbaac3c1c067fcdaeb3f966022e80e/src/api.rs#L1610) I've added to recrypt-rs showing using the bytes representation of `PrivateKey` and going to/from JSON.

It would be much nicer to be able to use serde on the recrypt types directly (`PublicKey`, `PrivateKey`, etc) which is what I thought you were going for with this feature. One way to accomplish this is to have the serde implementations delegate to `bytes()` (_ser_) and `new_from_slice()` (_de_). The test linked above shows how this would work.

A similar approach could be used for `PublicKey`.

**Comment by tpmccallum** [comment]
Hi @clintfred 
You are 100% spot on; not missing anything. 
I can confirm, as you mentioned, that this ser/des works on both PrivateKey and PublicKey when dealing in their bytes only ( `bytes()` and `bytes_x_y()` respectively). 

Initially I saw the recrypt keys as custom complex objects in need of ser/des. I now understand that aside from each key's bytes, each key's additional data serves a purpose internally and does not require ser/des for external transporting.

A few things to consider.
We could remember this PR as a reference for how to implement serde as an optional feature. Perhaps there will be a case in the future where a complex/custom struct will need serialising for external transporting back to the calling code etc.

It seems that, as you have tested, if the 3rd-party application (calling code) implements serde_json itself, then both PrivateKey and PublicKey bytes can be ser/des. These byte data structures of `[]`, `[[], []]` and `"[]"` seem to be simple enough for serde_json to ser/des without the need for additional serde code inside recrypt.

I see that this PR does increase the number of dependencies and therefore not merging will reduce dependencies and future maintenance etc.

Finally, perhaps I would go ahead (create a new PR) and just update the documentation in the lib.rs to demonstrate how a 3rd-party calling application can obtain PrivateKey and PublicKey bytes as Vec/String etc.

Happy for this to be closed. This has been very interesting and I have learned a lot about recrypt in the process. I am also really glad that we got a chance to tweak the `32-bit` & `64-bit` backend configuration as part of this process.

**Comment by tpmccallum** [comment]
I have the following solution though. This approach for the PublicKey x & y bytes is a little bit more complex that what we have to do for the PrivateKey bytes. But is still works and means that both PrivateKey and PublicKey can still undergo ser/des without the need for the optional serde feature (this PR). Please consider the following solution. 
```rust
    #[test]
    fn public_key_roundtrip_json_bytes() {
        // we don't have full serde support today for `PublicKey`, but here's an example of use serde_json directly on the bytes
        let r = Recrypt::new();
        let (_, pubk) = r.generate_key_pair().unwrap();
        // serialize to json "bytes"
        let pub_key_bytes_json_x = serde_json::to_vec(&pubk.bytes_x_y().0).unwrap();
        let pub_key_bytes_json_y = serde_json::to_vec(&pubk.bytes_x_y().1).unwrap();
        // serialize to string
        let pub_key_str_json_x = serde_json::to_string(&pubk.bytes_x_y().0).unwrap();
        let pub_key_str_json_y = serde_json::to_string(&pubk.bytes_x_y().1).unwrap();

        // deserialise from json bytes
        let from_bytes_json_x: Vec<u8> = serde_json::from_slice(&pub_key_bytes_json_x).unwrap();
        let from_bytes_json_y: Vec<u8> = serde_json::from_slice(&pub_key_bytes_json_y).unwrap();
        let from_bytes_json_x_as_tuple: &[u8] = &from_bytes_json_x;
        let from_bytes_json_y_as_tuple: &[u8] = &from_bytes_json_y;
        let combined_x_y = (from_bytes_json_x_as_tuple, from_bytes_json_y_as_tuple);
        let pub_key_from_bytes_json = PublicKey::new_from_slice(combined_x_y).unwrap();
        // check that serialized then deserialized data matches the original generated public key
        assert_eq!(&pub_key_from_bytes_json, &pubk);

        // deserialise from string
        let from_str_bytes_x: Vec<u8> = serde_json::from_str(&pub_key_str_json_x).unwrap();
        let from_str_bytes_y: Vec<u8> = serde_json::from_str(&pub_key_str_json_y).unwrap();
        let from_str_bytes_json_x_as_tuple: &[u8] = &from_str_bytes_x;
        let from_str_bytes_json_y_as_tuple: &[u8] = &from_str_bytes_y;
        let combined_x_y_2 = (from_str_bytes_json_x_as_tuple, from_str_bytes_json_y_as_tuple);
        let pub_key_from_str_bytes_json = PublicKey::new_from_slice(combined_x_y_2).unwrap();
        // check that serialized then deserialized data matches the original generated public key
        assert_eq!(&pub_key_from_str_bytes_json, &pubk);
    }
```
I have added this to the api.rs (this test passes) and I have also updated the documentation in the lib.rs.

Kind regards
Tim

**Comment by tpmccallum** [comment]
The unit tests for ser/des PrivateKey and PublicKey bytes is in [a new separate PR](https://github.com/IronCoreLabs/recrypt-rs/pull/120). Also the documentation which demonstrates how 3rd-party applications can perform ser/des is also in [a new separate PR](https://github.com/IronCoreLabs/recrypt-rs/pull/118)

**Pull request closed without merging**
